
CC = g++
CFLAGS = -lrt
TARGET = spg.out
TARGET2 = spgs.out
TARGET3 = sprgns.out
SOURCE = globalsch.c++

###############################################

g: ${SOURCE}
	clear
	${CC} -g -o ${TARGET} ${SOURCE} ${CFLAGS} 

clean:
	rm -f *.out {TARGET} 
